name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup sphinx
        run: pip install sphinx
      - name: Setup furo
        run: pip install furo
      - name: Setup sphinx-multiversion
        run: pip install sphinx-multiversion
      - name: Setup sphinx-multiversion
        run: pip install sphinx-multiversion
      - name: Generate Documentation
        run: sphinx-multiversion docs build
      - uses: actions/upload-artifact@v2
        name: Upload builded files to artifacts
        with:
          name: build
          path: build
          retention-days: 1
