name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup sphinx
        run: pip install sphinx
      - name: Setup furo
        run: pip install furo
      - name: Setup sphinx-multiversion
        run: pip install sphinx-multiversion
      - name: Generate Documentation
        run: sphinx-multiversion docs build
      - uses: actions/upload-artifact@v2
        name: Upload builded files to artifacts
        with:
          name: build
          path: build
          retention-days: 1
# Continuous Integration; Needs secrets to work properly.
# These secrets need to be set: SSH_HOST, SSH_PORT, SSH_USER,
# SSH_PRIVATE_KEY, SSH_KNOWN_HOST and DOCUMENTATION_REMOTE_HOST_PATH
# To get the known host execute: ssh-keyscan -H <IP_ADRESS>
#  ci:
#    name: Continuous Integration
#    runs-on: ubuntu-20.04
#    needs: build
#    steps:
#      - uses: actions/download-artifact@v2
#        name: Download builded documentation
#        with:
#          name: build
#      - name: Install SSH Key
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          known_hosts: ${{ secrets.SSH_KNOWN_HOST }} # To get the hash use: ssh-keyscan -H IP_ADDRESS_OF_HOST
#      - name: Deploy with rsync
#        run: rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DOCUMENTATION_REMOTE_HOST_PATH }}
